language: node_js
node_js:
  - "6"
  - "7"
  - "8"
before_install:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - npm install -g instagram-profilecrawl
script:
  - instagram-profilecrawl --method=api --output=nacimgoura_api.json
  - sleep 10
  - instagram-profilecrawl --method=selenium --output=nacimgoura_selenium.json
